### PR TITLE
Ensure co-author works in any GIT_COMMIT_MSG buffer

### LINKED ISSUE #5: [BUG]: Error when selecting someone as co author
### Description of the bug

Unable to add people as co author

My config: 
```
return {
  "2kabhishek/co-author.nvim",
  dependencies = {
    "stevearc/dressing.nvim",
    "nvim-telescope/telescope.nvim",
  },
  cmd = { "CoAuthor" },
}
```

### Steps To Reproduce

:CoAuthor
Select a person
Error appears (see picture)

### Additional Information

image

### PR DESCRIPTION
**Pull request by kevinrobayna**
## What/How/Why

Fixes: https://github.com/2KAbhishek/co-author.nvim/issues/5

Before it was trying to add the text outside of the buffer when the GIT_COMMIT_MSG buffer was invoked by lazygit. The buffer looks a bit different for some reason but it's still a GIT_COMMIT_MSG buffer.

This way the string is added right on top of the line you're currently located and it works either on a buffer created by git commit or the lazygit one.

### LazyGit

Selecting co-author for commit
Screenshot 2024-05-01 at 16 16 00

The author is added below the current line
Screenshot 2024-05-01 at 16 16 04

### git commit

Selecting co-author for commit
Screenshot 2024-05-01 at 16 16 18

The author is added below the current line

Screenshot 2024-05-01 at 16 16 21

### CODE REVIEW

File: lua/co-author/init.lua [hunk 1]
```diff
@@ -22,9 +22,7 @@ co_author.list = function()
         vim.ui.select(items, { prompt = 'Select Co-Author' }, function(item, _)
             if item ~= nil then
                 local string = 'Co-authored-by: ' .. item
-                local cursor_position = vim.api.nvim_win_get_cursor(0)
-                local line = cursor_position[1] + 1
-                local column = cursor_position[2]
+                local line, column = unpack(vim.api.nvim_win_get_cursor(0))
```
Comment (kevinrobayna) [inline lua/co-author/init.lua:25]: unpack just avoids us doing the [1] or [2] to get first attribute or second (also avoids seeing that lua starts index with 1 rather than 0 🤣)

File: lua/co-author/init.lua [hunk 2]
```diff
@@ -22,9 +22,7 @@ co_author.list = function()
         vim.ui.select(items, { prompt = 'Select Co-Author' }, function(item, _)
             if item ~= nil then
                 local string = 'Co-authored-by: ' .. item
-                local cursor_position = vim.api.nvim_win_get_cursor(0)
-                local line = cursor_position[1] + 1
```
Comment (kevinrobayna) [inline lua/co-author/init.lua:26]: the +1 here is what was causing the issue.

When debugging locally doing print(cursor_position_line, cursor_position_column)

it was printing always 2 0 wether it was lazygit or git commit UI so the issue was not getting the data but applying it when calling `vim.api.nvim_buf_set_lines(0, line, line, true, { string })`

File: lua/co-author/init.lua (hunk 1 above)
Comment (2KAbhishek) [reply lua/co-author/init.lua:25]: I wasn't aware of unpack, thanks for the fix!
